# 가입 회원 정보 테이블 USER_INFO
# 상품 판매 정보 테이블 ONLINE_SALE
# USER_INFO의 GENDER 컬럼은 비어있거나, 0(남자), 1(여자)
# 년, 월, 성별 별로 상품을 구매한 회원수 집계
# 년, 월, 성별 기준 오름차순
# 성별(GENDER)가 없는 경우 결과에서 제외
SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, A.GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO AS A
        INNER JOIN ONLINE_SALE AS B
        ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, A.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC