# 온라인 상품판매 정보 테이블 ONLINE_SALE
# 오프라인 상품판매 정보 테이블 OFFLINE_SALE
# 22년 3월의 온/오프라인 상품판매 데이터의 판매날짜, 상품ID, 유저ID, 판매량 출력
# OFFLINE_SALE 테이블의 USER_ID 값은 NULL로 표시
# 판매일 기준 오름차순, 상품ID 기준 오름차순, 유저ID 기준 오름차순
(SELECT LEFT(SALES_DATE, 10) AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%')

UNION ALL

(SELECT LEFT(SALES_DATE, 10) AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE LIKE '2022-03%')

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
