# 식품정보를 담은 FOOD_PRODUCT 테이블 
# 주문정보를 담은 FOOD_ORDER 테이블
# 생산일자(PRODUCT_DATE)가 2022년 5월인 식품들의 식품ID, 식품이름, 총매출(주문량*식품가격) 조회
# 총매출 기준 내림차순 정렬, 같다면 식품ID 기준 오름차순 정렬
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS A
        INNER JOIN FOOD_ORDER AS B
        ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE LIKE '2022-05%'
GROUP BY A.PRODUCT_ID

ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC